### ISSUE TITLE
[git convention] git flow (use rebase)

### ISSUE THREAD

**Issue by RGunny** [pro-gbm/Moogle#17]
### Rule
PR(Pull Request) 생성시, 아래 그림과 같이 Squash 혹은 Rebase 를 선택하여 Merge 한다.
- Squash : 작업한 commit 이 너무 많고 지저분할때.
- Rebase : 작업한 commit 그대로 head 위치를 PR 대상 브랜치로 재배치
![image](https://user-images.githubusercontent.com/40309812/187928957-d801159d-df09-4f10-aa9e-f5fa53abda19.png)

### Branch 전략
- master / develop / feature 를 사용.
1. 작업 시작 시 git issue 생성
2. 해당 issue에 맞는 feature 브랜치 생성 후 작업
3. 커밋시 리뷰어에게 리뷰 후 pull request

### 장점
- 독립적 개발 환경
기능(티켓) 단위로 독립적인 branch를 만들기 때문에 다른사람의 개발 결과에 영향을 받지 않는 독립적인 개발환경을 만들어주고, 이는 최소한의 방해로 각자의 개발에 몰입하게 해준다.
- 쉬운 추적
git graph가 가시적으로 명확히 보여 이슈 발생 시 어떤 기능에 문제가 있는 지 트래킹하고 `UNDO` 하기 쉽고 git 관리가 간편해진다.
그래프는 merge 대신 rebase를 사용하여 각 branch를 한 줄 된 그래프로 가시적인 관리가 용이하다.
- 배포 정책 및 CI/CD 연동
branch 별로 역할이 분리되어 있기 때문에 각 branch의 update에 맞춰 배포 & 테스트하기 좋다.

### References
- [우아한 git-flow](https://techblog.woowahan.com/2553/)
- [\[10분 테코톡\] 오리&코린의 Merge, Rebase, Cherry pick](https://www.youtube.com/watch?v=b72mDco4g78)
- [When do you use Git rebase instead of Git merge?](https://stackoverflow.com/questions/804115/when-do-you-use-git-rebase-instead-of-git-merge)

**Comment by junghyun100** [comment]
확인했어요. 이야기 했던 부분 정리해줘서 보기가 좋네요. 
고맙읍니다~
